version: 1

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF
formats:
- pdf

# Explicitly set the version of Python and its requirements
python:
  version: 3.8
  install:
  - method: pip
      path: .
      extra_requirements:
        - dev
